### ISSUE TITLE
Row is always updated when using JSON objects wrapped in POJOs with no explicit equals method

### ISSUE THREAD

**Issue by vpriscan** [vladmihalcea/hibernate-types#203]
Hello,

I am using PostgreSQL database and have a table with some jsonb data. 
I am using JsonBinaryType from hibernate-types-52 to map jsonb to POJO property in my entity.
```
@Entity
@TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
public class InstrumentEntity{
    ....
    @Type(type = "jsonb")
    @Column(name = "instrument_configuration", columnDefinition = "jsonb")
    private InstrumentConfiguration configuration;
    ....
}
```

My problem is the following, even when I am only trying to fetch (read) the entity from the database and don't update anything in it, when my transaction finishes, hibernate performs a row update! I know this because I see it in PostgreSQL log.
This is really unexpected and causes performance regression and even deadlocks in my application.

How to avoid performing row updates when I only want to fetch the data? 
If no JsonBinaryType is used, row is only updated if I update the entity, as expected.

**Comment by vladmihalcea** [comment]
You need to provide a replicating test case to prove the issue.

**Comment by vladmihalcea** [comment]
This issue is fixed by [this PR](https://github.com/vladmihalcea/hibernate-types/pull/198). It will be released in 2.10.0.

**Comment by gabrielfeitosa** [comment]
Hi @vladmihalcea, here a case with this behavior https://github.com/gabrielfeitoa/test-hibernate-types

**Comment by vladmihalcea** [comment]
@gabrielfeitosa Can you build the latest hibernste-types-52 and test with this SNAPSHOT version? Thd issue should be fixed.

**Comment by vladmihalcea** [comment]
@vpriscan @gabrielfeitosa I released 2.9.6 so you should test with that version. I created some tests that assert the number of statements and everything looks fine in the 2.9.6 release.

**Comment by gabrielfeitosa** [comment]
Hi @vladmihalcea, for me continues with the wrong behavior.

**Comment by vpriscan** [comment]
@vladmihalcea for me too wrong behaviour still occurs using 2.9.6.

**Comment by vladmihalcea** [comment]
I added [statement assertion](https://github.com/vladmihalcea/hibernate-types/commit/1b0fb16c03c4685488f6b9c67f0843c07117fdcb) for the JSON tests couldn't replicate the issue.

So, the next step is you building a replicating test case. You have to fork the project and create a new test like the ones I built that could replicate your behavior.

**Comment by vladmihalcea** [comment]
I managed to replicate it and [this commit](https://github.com/vladmihalcea/hibernate-types/commit/3fe18d50fb55f51d9485e128a2790cec61e7dd58) fixes the issue. This fix will be included in 2.9.7, but I will wait for one or two more fixes or improvements to release that.

You should give it a try and see if it works for you too. You can build the `hibernate-types-52` without running the tests and use the `2.9.7-SNAPSHOT` artifact to validate the fix.

**Comment by gabrielfeitosa** [comment]
@vladmihalcea thank you very much for the quick implementation, you're rock. The version 2.9.7-SNAPSHOT works for me and i tested 2.9.6 with equals and hashCode and works fine too. :rocket:

**Comment by vladmihalcea** [comment]
Great. I'll release it next week.

**Comment by vpriscan** [comment]
@vladmihalcea It works. Thank you a lot!

**Comment by vladmihalcea** [comment]
I'm glad to hear that. Enjoy using it and stay tuned for more!

**Comment by islamelsayed29** [comment]
@vladmihalcea 
I'm using the latest version of hibernate-types-52 and for wrapping the JSON object to POJO it works fine but the issue still exists when wrapping the JSON object to Set or List.

**Comment by vladmihalcea** [comment]
@islamelsayed29 Have you implemented equals and hashCode as stated by the documentation?

https://github.com/vladmihalcea/hibernate-types#best-practices

**Comment by islamelsayed29** [comment]
Thank you, It was missed and after implementing them it works fine.
Appreciate your response :)

**Comment by vladmihalcea** [comment]
I'm glad I could help
