### ISSUE TITLE
Add support for saving null JSON objects when using the JsonStringType

### ISSUE THREAD

**Issue by catta** [vladmihalcea/hibernate-types#210]
I have an entity with a String attribute mapped to a JSON column type into a **12.2 oracle** database. The column is nullable. When I try to persist an entity with null value on the attribute it throws exception with message "Invalid column type: 1111".

The version I used is 2.9.7

I've managed to reproduce the issue with test classes. Update the test `OracleJsonStringPropertyTest` to persist a new Book with null value for properties attribute, something like:
```
 new Book()
         .setIsbn("978-9730228236")
         .setProperties(null)
```

The test will fail with exception 
```
Caused by: java.sql.SQLException: Invalid column type: 1111
	at oracle.jdbc.driver.OracleStatement.getInternalType(OracleStatement.java:4121)
	at oracle.jdbc.driver.OraclePreparedStatement.setNullCritical(OraclePreparedStatement.java:4208)
	at oracle.jdbc.driver.OraclePreparedStatement.setNull(OraclePreparedStatement.java:4192)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.setNull(OraclePreparedStatementWrapper.java:1010)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.ttddyy.dsproxy.proxy.MethodUtils.proceedExecution(MethodUtils.java:13)
	at net.ttddyy.dsproxy.proxy.StatementProxyLogic.performQueryExecutionListener(StatementProxyLogic.java:237)
	at net.ttddyy.dsproxy.proxy.StatementProxyLogic.access$700(StatementProxyLogic.java:37)
	at net.ttddyy.dsproxy.proxy.StatementProxyLogic$1.execute(StatementProxyLogic.java:123)
	at net.ttddyy.dsproxy.listener.MethodExecutionListenerUtils.invoke(MethodExecutionListenerUtils.java:42)
	at net.ttddyy.dsproxy.proxy.StatementProxyLogic.invoke(StatementProxyLogic.java:120)
	at net.ttddyy.dsproxy.proxy.jdk.PreparedStatementInvocationHandler.invoke(PreparedStatementInvocationHandler.java:37)
	at com.sun.proxy.$Proxy18.setNull(Unknown Source)
	at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:77)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:286)
	at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:281)
	at org.hibernate.type.AbstractSingleColumnStandardBasicType.nullSafeSet(AbstractSingleColumnStandardBasicType.java:56)
	at org.hibernate.persister.entity.AbstractEntityPersister.dehydrate(AbstractEntityPersister.java:2843)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3121)

```
I checked the `OracleJsonStringPropertyTest` in `hibernate-types-43` and `hibernate-types-52` connecting to my **oracle 12.2** database.

**Comment by vladmihalcea** [comment]
Looks like an Oracle JDBC Driver issue. Try with plain JDBC and see if it works.

**Comment by catta** [comment]
> 
> 
> Looks like an Oracle JDBC Driver issue. Try with plain JDBC and see if it works.

Do you suggest or recommend a driver? A link to download or a maven artifact is perfect.

Thanks

**Comment by vladmihalcea** [comment]
I suggest you try various Drivers and see if the problem is fixed. Once you find the answer, you will have to report your findings so that others can benefit from your research.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by Adrodoc** [comment]
This seems to be fixed for `JsonStringType`, but is still an issue for `JsonType`.

**Comment by vladmihalcea** [comment]
@Adrodoc You can send a PR with a replicating test case based on the existing test for the `JsonStringType`.
