### ISSUE TITLE
Prevent NullPointerException caused by sqlArrayType in the ListArrayTypeDescriptor

### ISSUE THREAD

**Issue by niels1voo** [vladmihalcea/hibernate-types#320]
Hi Vlad,
I was integrating your library into our code and ran into an issue with ListArrayTypeDescriptor. I wrote a couple of tests to help debug the problem. I found that one instance of ListArrayTypeDescriptor, apparently the first as the log reveals, does not have setParameters called on it and so sqlArrayType is null, causing a null pointer exception.

[test branch](https://github.com/niels1voo/hibernate-types/tree/list_array_type_test)

```
DEBUG [Alice]: o.h.b.r.i.BootstrapServiceRegistryImpl - Implicitly destroying Boot-strap registry on de-registration of all child ServiceRegistries

java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "alias" is null

at org.postgresql.jdbc.TypeInfoCache.getTypeForAlias(TypeInfoCache.java:660)
at org.postgresql.jdbc.TypeInfoCache.getPGArrayType(TypeInfoCache.java:504)
at org.postgresql.jdbc.PgConnection.createArrayOf(PgConnection.java:1375)
at org.postgresql.jdbc.PgConnection.createArrayOf(PgConnection.java:1399)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at net.ttddyy.dsproxy.proxy.ConnectionProxyLogic.performQueryExecutionListener(ConnectionProxyLogic.java:112)
at net.ttddyy.dsproxy.proxy.ConnectionProxyLogic.access$000(ConnectionProxyLogic.java:25)
at net.ttddyy.dsproxy.proxy.ConnectionProxyLogic$1.execute(ConnectionProxyLogic.java:50)
at net.ttddyy.dsproxy.listener.MethodExecutionListenerUtils.invoke(MethodExecutionListenerUtils.java:42)
at net.ttddyy.dsproxy.proxy.ConnectionProxyLogic.invoke(ConnectionProxyLogic.java:47)
at net.ttddyy.dsproxy.proxy.jdk.ConnectionInvocationHandler.invoke(ConnectionInvocationHandler.java:25)
at com.sun.proxy.$Proxy6.createArrayOf(Unknown Source)
at com.vladmihalcea.hibernate.type.array.internal.ArraySqlTypeDescriptor$1.doBind(ArraySqlTypeDescriptor.java:38)
at org.hibernate.type.descriptor.sql.BasicBinder.bind(BasicBinder.java:73)
at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:276)
at org.hibernate.type.AbstractStandardBasicType.nullSafeSet(AbstractStandardBasicType.java:271)
at org.hibernate.param.PositionalParameterSpecification.bind(PositionalParameterSpecification.java:55)
at org.hibernate.loader.hql.QueryLoader.bindParameterValues(QueryLoader.java:648)
at org.hibernate.loader.Loader.bindPreparedStatement(Loader.java:2139)
at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2116)
at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2048)
at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2026)
at org.hibernate.loader.Loader.doQuery(Loader.java:951)
at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:352)
at org.hibernate.loader.Loader.doList(Loader.java:2857)
at org.hibernate.loader.Loader.doList(Loader.java:2839)
at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2671)
at org.hibernate.loader.Loader.list(Loader.java:2666)
at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1412)
at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1565)
at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1533)
at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1581)
at com.vladmihalcea.hibernate.type.array.ListArrayTypeTest.lambda$testListArrayQuery$1(ListArrayTypeTest.java:133)
at com.vladmihalcea.hibernate.type.util.AbstractTest.doInJPA(AbstractTest.java:451)
at com.vladmihalcea.hibernate.type.array.ListArrayTypeTest.testListArrayQuery(ListArrayTypeTest.java:129)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by vladmihalcea** [comment]
It's great that you managed to replicate it with a test case. Now, you should investigate why `setParameters` is called in the tests that I wrote and not in yours.

If you can find the issue, please send a Pull Request with a fix proposal. I'll check it out when it's done.

**Comment by vladmihalcea** [comment]
Fixed.

**Comment by drunkhacker** [comment]
Hello, I think this issue is still not fixed. As of version 2.12.1 for hibernate-types-52, `sqlArrayType` is still null, which needs to be set at `setParameterValues` function.

**Comment by vladmihalcea** [comment]
@drunkhacker If you can provide a replicating test case, then I will open a new issue for it.
